import json
import logging
from typing import List, Dict, Any, Optional

# Assuming these imports exist in your project structure
# from planner import Planner
# from worker import Worker
# from synthesizer import Synthesizer

logger = logging.getLogger(__name__)

class Orchestrator:
    def __init__(self, planner, worker_factory, synthesizer):
        """
        Initialize the Orchestrator.
        
        Args:
            planner: Instance of the Planner class responsible for generating task lists.
            worker_factory: A callable or factory that returns Worker instances.
            synthesizer: Instance of the Synthesizer class responsible for combining results.
        """
        self.planner = planner
        self.worker_factory = worker_factory
        self.synthesizer = synthesizer

    def execute(self, query: str) -> str:
        """
        Execute a query by planning, executing tasks, and synthesizing results.
        
        Args:
            query: The user's input query.
            
        Returns:
            The synthesized final answer.
        """
        # Step 1: Planning with Critique (Improvement #2)
        task_list = self._plan_with_critique(query)
        
        if not task_list:
            return "No valid tasks could be generated."

        # Step 2: Execution with Stall Detection (Improvement #1)
        completed_results = self._execute_tasks(task_list)
        
        if len(completed_results) == 0:
            logger.warning("Stall detected: No results returned from workers. Triggering retry.")
            return self._handle_stall(query, task_list)

        # Step 3: Synthesis with Robustness (Improvement #3)
        final_answer = self.synthesizer.synthesize(completed_results, query)
        return final_answer

    def _plan_with_critique(self, query: str) -> List[Dict[str, Any]]:
        """
        Generate a task list and validate it using a critique step.
        
        Args:
            query: The user's input query.
            
        Returns:
            A list of validated tasks or an empty list if validation fails.
        """
        # Generate initial plan
        raw_plan = self.planner.plan(query)
        
        # Critique the plan for structural integrity
        critique_result = self._critique_plan(raw_plan, query)
        
        if not critique_result.get("is_valid", False):
            logger.warning(f"Plan validation failed: {critique_result.get('reason', 'Unknown reason')}")
            return []
            
        return critique_result.get("task_list", [])

    def _critique_plan(self, raw_plan: List[Dict[str, Any]], query: str) -> Dict[str, Any]:
        """
        Evaluate the generated task list for circular dependencies, missing descriptions, 
        or over-decomposition.
        
        Args:
            raw_plan: The initial list of tasks generated by the planner.
            query: The original user query.
            
        Returns:
            A dictionary containing validation status and potentially corrected task list.
        """
        # In a real implementation, this might call an LLM or run static analysis
        # Here we simulate the critique logic
        
        if not raw_plan:
            return {"is_valid": False, "reason": "Empty plan"}
            
        for i, task in enumerate(raw_plan):
            if not task.get("description"):
                return {"is_valid": False, "reason": f"Task {i} missing description"}
            # Add more checks as needed (e.g., circular deps)
            
        return {"is_valid": True, "task_list": raw_plan}

    def _execute_tasks(self, task_list: List[Dict[str, Any]]) -> List[Any]:
        """
        Execute tasks and collect results.
        
        Args:
            task_list: The list of tasks to execute.
            
        Returns:
            A list of results from the workers.
        """
        completed_results = []
        for task in task_list:
            try:
                worker = self.worker_factory(task)
                result = worker.execute()
                completed_results.append(result)
            except Exception as e:
                logger.error(f"Worker execution failed for task {task.get('id', 'unknown')}: {e}")
                # Do not add empty results to the list if they are truly failures
                # But per requirement, we check len(completed_results) == 0 after dispatch
                # So we might append None or empty string to track attempted tasks?
                # Let's assume workers return empty strings on failure.
                completed_results.append("") 
        
        return completed_results

    def _handle_stall(self, query: str, previous_task_list: List[Dict[str, Any]]) -> str:
        """
        Handle stall detection by retrying with error context.
        
        Args:
            query: The original user query.
            previous_task_list: The task list that failed to produce results.
            
        Returns:
            A fallback message or result from re-planning.
        """
        # Re-plan with explicit error context
        error_context = f"Previous plan failed to produce results: {previous_task_list}"
        retry_query = f"{query}. Note: Previous attempt failed. {error_context}"
        
        # Re-plan
        retry_plan = self._plan_with_critique(retry_query)
        
        if not retry_plan:
            return "System unable to generate valid tasks after retry."
            
        # Re-execute
        retry_results = self._execute_tasks(retry_plan)
        
        if len(retry_results) == 0:
            return "Critical failure: System stalled again after retry."
            
        # Synthesize new results
        final_answer = self.synthesizer.synthesize(retry_results, query)
        return final_answer

    def _synthesize_with_robustness(self, completed_results: List[Any], query: str) -> str:
        """
        Wrapper for synthesizer to handle robustness checks if needed outside.
        However, the prompt update suggests updating the Synthesizer's internal logic or prompt.
        This method is kept for reference if external validation is preferred.
        """
        # Check for empty replicas
        valid_replicas = [r for r in completed_results if r and str(r).strip()]
        
        if len(valid_replicas) < 1: # k_factor could be configurable, defaulting to 1
            return "No valid results available."
            
        return self.synthesizer.synthesize(completed_results, query)