import json
import logging
from typing import List, Dict, Any, Optional

# Assuming these imports exist in your project structure
# from planner import Planner
# from worker import Worker
# from synthesizer import Synthesizer

logger = logging.getLogger(__name__)

class Orchestrator:
    def __init__(self, planner, worker, synthesizer):
        self.planner = planner
        self.worker = worker
        self.synthesizer = synthesizer
        # Configuration for retry logic
        self.max_retries = 3
        self.retry_count = 0

    def execute(self, query: str) -> str:
        """
        Executes the full OCO pipeline with improved stall detection and validation.
        """
        try:
            # Step 1: Planning
            plan = self.planner.plan(query)
            
            # Insight 2: Pre-Execution Plan Validation
            validated_plan = self._validate_plan(plan)
            if not validated_plan:
                logger.warning("Plan validation failed after retries. Returning error.")
                return "Error: Failed to generate a valid execution plan."

            tasks = validated_plan.get('task_list', [])
            
            # Step 2: Dispatch and Execution with Stall Detection
            completed_results = []
            
            # Insight 1: Stall Detection & Recovery
            if not tasks:
                logger.warning("Planner generated empty task list.")
                return "Error: No tasks generated by planner."

            for task in tasks:
                result = self.worker.execute(task)
                completed_results.append(result)

            # Check for silent failures or empty results across all workers
            if len(completed_results) == 0:
                logger.error("Stall detected: No results returned from workers.")
                return self._handle_stall(query, tasks)

            # Filter out None/empty results if necessary before synthesis
            valid_replicas = [r for r in completed_results if r and len(str(r)) > 0]
            
            # Step 3: Synthesis with Robustness
            final_answer = self.synthesizer.synthesize(query, valid_replicas)
            return final_answer

        except Exception as e:
            logger.error(f"Orchestrator execution failed: {str(e)}")
            return f"Error: Internal system failure. Details: {str(e)}"

    def _validate_plan(self, plan: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """
        Insight 2: Inserts a lightweight critique step to validate the generated task_list.
        Checks for circular dependencies, missing descriptions, or over-decomposition.
        """
        max_validation_attempts = 3
        attempt = 0
        
        while attempt < max_validation_attempts:
            # Call the Critique Prompt logic here (simulated)
            critique_result = self._run_critique(plan)
            
            if critique_result.get('is_valid', False):
                return plan
            
            # If invalid, re-plan with error context
            logger.info(f"Plan validation failed. Attempt {attempt + 1}. Re-planning...")
            error_context = critique_result.get('feedback', "Invalid plan structure.")
            plan = self.planner.replan(plan['query'], error_context)
            attempt += 1
            
        return None

    def _run_critique(self, plan: Dict[str, Any]) -> Dict[str, Any]:
        """
        Simulates the CRITIQUE_PROMPT step.
        In a real implementation, this would call an LLM with the CRITIQUE_PROMPT.
        """
        # Placeholder for actual LLM critique logic
        # Check for basic structural integrity
        tasks = plan.get('task_list', [])
        if not tasks:
            return {'is_valid': False, 'feedback': 'No tasks generated.'}
        
        for task in tasks:
            if not task.get('description'):
                return {'is_valid': False, 'feedback': 'Task missing description.'}
            # Add more checks for circular dependencies here if graph-based
        
        return {'is_valid': True, 'feedback': ''}

    def _handle_stall(self, query: str, failed_tasks: List[Dict]) -> str:
        """
        Insight 1: Handles stall detection by transitioning to retry state.
        Triggers re-planning with explicit error context.
        """
        logger.warning("Initiating stall recovery protocol.")
        
        # Attempt to re-plan with context of failure
        error_context = f"Previous execution stalled. Tasks attempted: {[t.get('id') for t in failed_tasks]}. No results returned."
        
        try:
            new_plan = self.planner.replan(query, error_context)
            if not new_plan or not new_plan.get('task_list'):
                return "Error: Recovery planning failed. System unable to generate new tasks."
            
            # Retry execution once with the new plan
            logger.info("Retrying execution with re-planned tasks.")
            retry_results = []
            for task in new_plan['task_list']:
                result = self.worker.execute(task)
                retry_results.append(result)
            
            if not retry_results or all(not r for r in retry_results):
                return "Error: System stalled again after recovery attempt."
                
            # Proceed to synthesis with retry results
            valid_replicas = [r for r in retry_results if r and len(str(r)) > 0]
            final_answer = self.synthesizer.synthesize(query, valid_replicas)
            return final_answer
            
        except Exception as e:
            logger.error(f"Stall recovery failed: {str(e)}")
            return "Error: Critical failure during stall recovery."

    def _check_synthesis_input(self, replicas: List[Any]) -> bool:
        """
        Insight 3: Helper to check if synthesis input is robust.
        Returns False if replicas are empty or insufficient.
        """
        # k_factor could be a configurable parameter
        k_factor = 1 
        return len(replicas) >= k_factor and any(r for r in replicas)